"""中英文字典 — xTBridge 界面文本。"""

TR = {
    # 窗口
    "win_title": {"zh": "xTBridge — Gaussian + xTB + 3D 可视化", "en": "xTBridge — Gaussian + xTB + 3D Visualization"},
    # 标签
    "tab_gaussian": {"zh": "\u2002\u2002\u269B\uFE0F Gaussian + xTB\u2002\u2002", "en": "\u2002\u2002\u269B\uFE0F Gaussian + xTB\u2002\u2002"},
    "tab_xtb": {"zh": "\u2002\u2002\U0001F680 xTB \u72EC\u7ACB\u2002\u2002", "en": "\u2002\u2002\U0001F680 xTB Standalone\u2002\u2002"},
    "tab_orca": {"zh": "\u2002\u2002\U0001F40B ORCA Submit\u2002\u2002", "en": "\u2002\u2002\U0001F40B ORCA Submit\u2002\u2002"},
    "lang_btn": {"zh": "EN", "en": "中"},
    # 通用
    "browse": {"zh": "📂 浏览", "en": "📂 Browse"},
    "setup": {"zh": "⚙️ 设置", "en": "⚙️ Setup"},
    "run": {"zh": "\u2BC8 运行", "en": "\u2BC8 Run"},
    "abort": {"zh": "■ 终止", "en": "■ Abort"},
    "close": {"zh": "关闭", "en": "Close"},
    "reset_view": {"zh": "重置视图", "en": "Reset View"},
    "preview": {"zh": "预览命令", "en": "Preview"},
    "clear_log": {"zh": "🗑 清除", "en": "🗑 Clear"},
    "open_folder": {"zh": "在文件夹中打开", "en": "Open Folder"},
    "save_gjf": {"zh": "导出 GJF", "en": "Export GJF"},
    "ready": {"zh": "就绪", "en": "Ready"},
    "running": {"zh": "运行中", "en": "Running..."},
    "done": {"zh": "计算完成", "en": "Completed"},
    "aborted": {"zh": "已终止", "en": "Aborted"},
    "error": {"zh": "错误", "en": "Error"},
    "hint": {"zh": "提示", "en": "Notice"},
    # 文件
    "input_file": {"zh": "输入文件", "en": "Input File"},
    "placeholder_gjf": {"zh": "选择 .gjf 文件...", "en": "Select .gjf file..."},
    "placeholder_xyz": {"zh": "选择 xyz / gjf / mol / sdf / pdb / coord ...", "en": "Select xyz / gjf / mol / sdf / pdb / coord ..."},
    # 程序路径
    "prog_path": {"zh": "程序路径", "en": "Program Paths"},
    "g16_path": {"zh": "高斯 (g16.exe):", "en": "Gaussian (g16.exe):"},
    "xtb_path": {"zh": "xTB (xtb.exe):", "en": "xTB (xtb.exe):"},
    "placeholder_g16": {"zh": "如 E:\\g16w\\g16.exe", "en": "e.g. E:\\g16w\\g16.exe"},
    "placeholder_xtb": {"zh": "如 E:\\teach\\xtb-...\\bin\\xtb.exe", "en": "e.g. E:\\teach\\xtb-...\\bin\\xtb.exe"},
    "xtb2_path": {"zh": "xTB 路径", "en": "xTB Path"},
    "placeholder_xtb2": {"zh": "xtb.exe 路径", "en": "xtb.exe path"},
    # 计算设置
    "calc_setup": {"zh": "计算设置", "en": "Calculation Setup"},
    "method": {"zh": "方法", "en": "Method"},
    "calc_type": {"zh": "计算类型", "en": "Calc Type"},
    "workdir": {"zh": "工作目录", "en": "Work Dir"},
    "placeholder_workdir": {"zh": "计算执行目录", "en": "Calculation directory"},
    "charge": {"zh": "电荷", "en": "Charge"},
    "mult": {"zh": "多重度:", "en": "Multiplicity:"},
    "unpaired": {"zh": "未成对电子", "en": "Unpaired e⁻"},
    "scf_acc": {"zh": "SCF 精度:", "en": "SCF Acc:"},
    "etemp": {"zh": "电子温度 (K):", "en": "Elec. Temp (K):"},
    "etemp_short": {"zh": "电子温度 (K)", "en": "Elec. Temp (K)"},
    "solvation": {"zh": "溶剂化:", "en": "Solvation:"},
    "solvation_short": {"zh": "溶剂化", "en": "Solvation"},
    "solvent": {"zh": "溶剂:", "en": "Solvent:"},
    "solvent_short": {"zh": "溶剂", "en": "Solvent"},
    "threads": {"zh": "线程数:", "en": "Threads:"},
    "parallel": {"zh": "并行线程", "en": "Parallel Thrs"},
    "extra_args": {"zh": "额外参数:", "en": "Extra Args:"},
    "output_opts": {"zh": "输出选项", "en": "Output"},
    "route": {"zh": "计算关键字:", "en": "Route:"},
    "placeholder_route": {"zh": "如 opt=(qst2,noeigen) geom=connectivity", "en": "e.g. opt=(qst2,noeigen) geom=connectivity"},
    "tooltip_route": {"zh": "高斯路由段关键字 (不支持 freq 等需要 Hessian 的关键字)", "en": "Gaussian route keywords (freq/Hessian not supported)"},
    "gfn_level": {"zh": "GFN 级别:", "en": "GFN Level:"},
    "tooltip_chrg": {"zh": "覆盖 gjf 中的电荷 (0 = 使用 gjf 值)", "en": "Override gjf charge (0 = use gjf value)"},
    "tooltip_mult": {"zh": "自旋多重度，从 gjf 自动读取", "en": "Spin multiplicity, auto-read from gjf"},
    "placeholder_extra": {"zh": "如 --molden —json —verbose", "en": "e.g. --molden --json --verbose"},
    # 气相
    "gas_phase": {"zh": "气相 (Gas Phase)", "en": "Gas Phase"},
    # 输出
    "calc_output": {"zh": "计算输出", "en": "Output"},
    "xtb_output": {"zh": "xTB 输出", "en": "xTB Output"},
    # 可视化
    "mol_structure": {"zh": "分子结构", "en": "Molecular Structure"},
    "reactant": {"zh": "反应物", "en": "Reactant"},
    "product": {"zh": "产物", "en": "Product"},
    "rotate_hint": {"zh": "左键旋转 | 右键平移 | 滚轮缩放", "en": "LMB rotate | RMB pan | Scroll zoom"},
    "no_mol": {"zh": "(未加载分子)", "en": "(No molecule loaded)"},
    "no_parse": {"zh": "(无法解析分子结构)", "en": "(Cannot parse structure)"},
    "qst2_hint": {"zh": "qst2 — 选项卡切换视角，独立旋转/缩放", "en": "qst2 — Switch tab for view, independent rotation/zoom"},
    "qst2_hint_short": {"zh": "qst2 — 选项卡切换视角", "en": "qst2 — Switch tab"},
    # 分子信息
    "mol_info_single": {"zh": "{formula}  |  {natoms} 个原子  |  {nbonds} 个键", "en": "{formula}  |  {natoms} atoms  |  {nbonds} bonds"},
    "mol_info_qst2": {"zh": "{formula}  |  {nr}+{np} 个原子  |  qst2 双结构", "en": "{formula}  |  {nr}+{np} atoms  |  qst2 dual"},
    # 文件选择器
    "open_gjf": {"zh": "选择 gjf 文件", "en": "Open gaussian input"},
    "open_file": {"zh": "选择 {name}", "en": "Select {name}"},
    "open_coord": {"zh": "选择坐标文件", "en": "Select coordinate file"},
    "open_workdir": {"zh": "选择工作目录", "en": "Select working directory"},
    "open_product": {"zh": "选择产物结构", "en": "Select product structure"},
    "gaussian_filter": {"zh": "Gaussian Input (*.gjf *.com);;All (*)", "en": "Gaussian Input (*.gjf *.com);;All (*)"},
    "coord_filter": {"zh": "坐标文件 (*.xyz *.gjf *.com *.mol *.sdf *.pdb *.coord);;All (*)", "en": "Coordinate files (*.xyz *.gjf *.com *.mol *.sdf *.pdb *.coord);;All (*)"},
    "exe_filter": {"zh": "Exe (*.exe);;All (*)", "en": "Exe (*.exe);;All (*)"},
    # 错误消息
    "err_gjf_notfound": {"zh": "gjf 文件不存在:", "en": "GJF file not found:"},
    "err_g16_notfound": {"zh": "高斯程序不存在:", "en": "Gaussian executable not found:"},
    "err_xtb_notfound": {"zh": "xTB 程序不存在:", "en": "xTB executable not found:"},
    "err_missing_script": {"zh": "未找到 gau_xtb.py，请从\nhttps://github.com/Stardust0831/gau_xtb 下载\n放到程序同目录。", "en": "gau_xtb.py not found. Please download from\nhttps://github.com/Stardust0831/gau_xtb\nand place in the same directory."},
    "err_read_gjf": {"zh": "无法读取 gjf:", "en": "Cannot read gjf:"},
    "err_no_route": {"zh": "未找到路由段 (以 # 开头的 route section)。\n请检查 .gjf 格式。", "en": "No route section found (starting with #).\nPlease check .gjf format."},
    "err_scan_empty": {"zh": "请填写 xTB scan 的 $constrain/$scan 输入块。", "en": "Please fill in the $constrain/$scan block for the xTB scan."},
    "err_write_tmp": {"zh": "无法写入临时 gjf:", "en": "Cannot write temp gjf:"},
    "err_no_input": {"zh": "请选择输入文件", "en": "Please select an input file"},
    "err_invalid_workdir": {"zh": "工作目录无效:", "en": "Invalid work directory:"},
    "err_no_coord": {"zh": "无法从 gjf 解析坐标", "en": "Cannot parse coordinates from gjf"},
    "err_param": {"zh": "参数错误", "en": "Parameter Error"},
    "already_running": {"zh": "已有计算在运行", "en": "A calculation is already running"},
    "launch_error": {"zh": "启动错误", "en": "Launch Error"},
    "err_crash": {"zh": "程序崩溃:", "en": "Program crashed:"},
    # 正常结束
    "normal_end": {"zh": "正常结束", "en": "Normal termination"},
    "exit_code": {"zh": "异常退出 (code={code})", "en": "Error exit (code={code})"},
    # 最终结构窗口
    "opt_structure": {"zh": "优化最终结构", "en": "Optimized Structure"},
    "xtb_opt_title": {"zh": "xTB 优化结构 (xtbopt.xyz)", "en": "xTB Optimized Structure (xtbopt.xyz)"},
    "from_file": {"zh": "从 {name} 提取 - {n} 个原子 | {b} 个键", "en": "From {name} - {n} atoms | {b} bonds"},
    # compute types
    "ct_single": {"zh": "单点能 (SP)", "en": "Single Point"},
    "ct_opt": {"zh": "结构优化 (Opt)", "en": "Optimization"},
    "ct_scan": {"zh": "柔性扫描 (Scan)", "en": "Relaxed Scan"},
    "scan_hint": {"zh": "xTB xcontrol 输入 ($constrain/$scan 块):", "en": "xTB xcontrol input ($constrain/$scan block):"},
    "scan_force_k": {"zh": "约束力常数", "en": "Force const."},
    "scan_viewer_title": {"zh": "扫描能量变化图 ({steps} 步)", "en": "Scan Energy Profile ({steps} steps)"},
    "scan_step_info": {"zh": "Step {step}: E = {e:.8f} Eh,  ΔE = {e_rel:.2f} kcal/mol", "en": "Step {step}: E = {e:.8f} Eh,  ΔE = {e_rel:.2f} kcal/mol"},
    "ct_ts": {"zh": "过渡态搜索 (TS)", "en": "TS Search"},
    "ct_reactor": {"zh": "反应路径 (Reactor)", "en": "Reactor Path"},
    "ct_md": {"zh": "分子动力学 (MD)", "en": "Molecular Dynamics"},
    "ct_modef": {"zh": "Mode Following", "en": "Mode Following"},
    "ct_path": {"zh": "NEB-TS (Path)", "en": "NEB-TS (Path)"},
    # TS params
    "ts_product": {"zh": "产物结构文件:", "en": "Product structure:"},
    "ts_modef": {"zh": "Mode Following 模式号:", "en": "Mode Following mode#:"},
    # 默认 route
    "default_route": {"zh": "opt", "en": "opt"},
    # 预览
    "preview_title": {"zh": "=== Command Preview ===", "en": "=== Command Preview ==="},
    "preview_workdir": {"zh": "工作目录:", "en": "Working Directory:"},
    "preview_cmd": {"zh": "命令:", "en": "Command:"},

    # ── ORCA Tab ──
    "orca_file": {"zh": "输入文件", "en": "Input File"},
    "orca_ph_file": {"zh": "选择 .gjf / .xyz 文件...", "en": "Select .gjf / .xyz file..."},
    "orca_path": {"zh": "ORCA 路径", "en": "ORCA Path"},
    "orca_job": {"zh": "作业设置", "en": "Job Settings"},
    "orca_method": {"zh": "方法:", "en": "Method:"},
    "orca_basis": {"zh": "基组:", "en": "Basis:"},
    "orca_job_type": {"zh": "任务类型:", "en": "Job Type:"},
    "orca_product": {"zh": "产物文件:", "en": "Product file:"},
    "orca_nimages": {"zh": "镜像数:", "en": "NImages:"},
    "orca_free_end": {"zh": "自由端点", "en": "Free-End"},
    "orca_extra": {"zh": "附加关键词:", "en": "Extra:"},
    "orca_ph_extra": {"zh": "%scf maxiter 200 end  或  TightSCF ...", "en": "%scf maxiter 200 end  or  TightSCF ..."},
    "orca_mol_info": {"zh": "分子信息", "en": "Molecule Info"},
    "orca_no_mol": {"zh": "(未加载分子)", "en": "(no molecule loaded)"},
    "orca_parse_fail": {"zh": "(解析失败)", "en": "(parse failed)"},
    "orca_run": {"zh": "\u2BC8 运行 ORCA", "en": "\u2BC8 Run ORCA"},
    "orca_abort": {"zh": "■ 终止", "en": "■ Abort"},
    "orca_preview": {"zh": "预览输入", "en": "Preview Input"},
    "orca_ofakeg": {"zh": "OfakeG → GV", "en": "OfakeG → GV"},
    "orca_ofakeg_tip": {"zh": "将已有 .out 转换为 GaussView 兼容格式", "en": "Convert existing .out to GaussView-compatible format"},
    "orca_status_ready": {"zh": "就绪", "en": "Ready"},
    "orca_output": {"zh": "ORCA 输出", "en": "ORCA Output"},
    "orca_3d_view": {"zh": "3D 分子视图", "en": "3D Molecular View"},
    "orca_rotate_hint": {"zh": "左键:旋转 | 右键:平移 | 滚轮:缩放", "en": "LMB: Rotate | RMB: Pan | Wheel: Zoom"},
    "orca_style": {"zh": "样式:", "en": "Style:"},
    "orca_reset_view": {"zh": "重置视角", "en": "Reset View"},
    "orca_qst_reactant": {"zh": "反应物", "en": "Reactant"},
    "orca_qst_product": {"zh": "产物", "en": "Product"},
    "orca_qst_detected": {"zh": "    [QST2: 反应物 + 产物]", "en": "    [QST2: reactant + product]"},
    "orca_status_run": {"zh": "运行中...", "en": "Running..."},
    "orca_status_abort": {"zh": "已中止", "en": "Aborted"},
    "orca_status_ok": {"zh": "正常终止", "en": "Normal termination"},
    "orca_status_ok_gv": {"zh": "正常终止 + GaussView 就绪", "en": "Normal termination + GaussView ready"},
    "orca_status_err": {"zh": "错误 (代码={code})", "en": "Error (code={code})"},
    "orca_dlg_preview": {"zh": "ORCA 输入预览", "en": "ORCA Input Preview"},
    "orca_fd_input": {"zh": "选择输入文件", "en": "Select input file"},
    "orca_fd_product": {"zh": "选择产物文件", "en": "Select product file"},
    "orca_fd_out": {"zh": "选择 ORCA .out 文件", "en": "Select ORCA .out file"},
    "orca_fd_exe": {"zh": "选择 {name}", "en": "Select {name}"},
    "orca_filter_all": {"zh": "所有支持 (*.gjf *.xyz *.com *.mol);;Gaussian Input (*.gjf *.com);;XYZ (*.xyz);;All (*)",
                        "en": "All supported (*.gjf *.xyz *.com *.mol);;Gaussian Input (*.gjf *.com);;XYZ (*.xyz);;All (*)"},
    "orca_filter_xyz": {"zh": "XYZ (*.xyz);;Gaussian Input (*.gjf *.com);;All (*)",
                        "en": "XYZ (*.xyz);;Gaussian Input (*.gjf *.com);;All (*)"},
    "orca_filter_out": {"zh": "ORCA Output (*.out);;All (*)", "en": "ORCA Output (*.out);;All (*)"},
    "orca_filter_exe": {"zh": "Exe (*.exe);;All (*)", "en": "Exe (*.exe);;All (*)"},
    "orca_log_job": {"zh": "ORCA 作业提交", "en": "ORCA job submission"},
    "orca_log_time": {"zh": "时间:", "en": "Time:"},
    "orca_log_orca": {"zh": "ORCA:", "en": "ORCA:"},
    "orca_log_input": {"zh": "输入:", "en": "Input:"},
    "orca_log_work": {"zh": "工作目录:", "en": "Work:"},
    "orca_mem": {"zh": "内存(MB):", "en": "Mem (MB):"},
    "orca_log_preview": {"zh": "--- ORCA 输入预览 ---", "en": "--- ORCA Input Preview ---"},
    "orca_log_end_preview": {"zh": "--- 预览结束 ---", "en": "--- End Preview ---"},
    "orca_log_ok": {"zh": "[OK] ORCA 已正常终止", "en": "[OK] ORCA terminated normally"},
    "orca_log_err": {"zh": "[ERR] ORCA 退出代码:", "en": "[ERR] ORCA exit code:"},
    "orca_log_ofakeg_out": {"zh": "[OfakeG] GaussView 兼容输出:", "en": "[OfakeG] GaussView-compatible output:"},
    "orca_msg_no_mol": {"zh": "未加载分子。", "en": "No molecule loaded."},
    "orca_msg_no_orca": {"zh": "未找到 ORCA:\n", "en": "ORCA not found:\n"},
    "orca_msg_warn": {"zh": "警告", "en": "Warning"},
    "orca_msg_err": {"zh": "错误", "en": "Error"},
    "orca_msg_ofakeg": {"zh": "未找到 OfakeG", "en": "OfakeG not found"},
    "orca_ofakeg_path": {"zh": "OfakeG 路径:", "en": "OfakeG Path:"},
    "orca_msg_neb": {"zh": "NEB-TS 需要产物结构。\n请提供含两个坐标块的 QST2 .gjf，\n或单独指定产物文件。",
                      "en": "NEB-TS requires product structure.\nEither provide a QST2 .gjf or specify a product file."},
    "orca_neb_title": {"zh": "NEB-TS 收敛结构", "en": "NEB-TS Converged Structure"},
    "orca_neb_from_file": {"zh": "{name}: {n} 原子, {b} 键", "en": "{name}: {n} atoms, {b} bonds"},
    "orca_scan_hint": {"zh": "%geom Scan 块 (可从 Gaussian modredundant 自动转换):", "en": "%geom Scan block (auto-converted from Gaussian modredundant):"},
    "orca_mol_info_fmt": {"zh": "{formula}  |  {natoms} 原子  |  {nbonds} 键",
                          "en": "{formula}  |  {natoms} atoms  |  {nbonds} bonds"},
}
